name: batch collector
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/batch-collector.yml
jobs:
    collect:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 1
            fail-fast: false
            matrix:
                package: 
                  - acre
                  - afula
                  - arad
                  - arraba
                  - ashdod
                  - ashkelon
                  - baqa-al-gharbiyye
                  - bat-yam
                  - beersheba
                  - beit-shean
                  - beit-shemesh
                  - bnei-brak
                  - dimona
                  - eilat
                  - elad
                  - givat-shmuel
                  - givatayim
                  - hadera
                  - haifa
                  - herzliya
                  - hod-hasharon
                  - holon
                  - jerusalem
                  - kafr-qasim
                  - karmiel
                  - kfar-saba
                  - kfar-yona
                  - kiryat-ata
                  - kiryat-bialik
                  - kiryat-gat
                  - kiryat-malakhi
                  - kiryat-motzkin
                  - kiryat-ono
                  - kiryat-shmona
                  - kiryat-yam
                  - lod
                  - maalot-tarshiha
                  - migdal-haemek
                  - modiin-maccabim-reut
                  - nahariya
                  - nazareth
                  - nesher
                  - ness-ziona
                  - netanya
                  - netivot
                  - nof-hagalil
                  - ofakim
                  - or-akiva
                  - or-yehuda
                  - petah-tikva
                  - qalansawe
                  - raanana
                  - rahat
                  - ramat-gan
                  - ramat-hasharon
                  - ramla
                  - rehovot
                  - rishon-lezion
                  - rosh-haayin
                  - safed
                  - sakhnin
                  - sderot
                  - shefa-amr
                  - tamra
                  - tayibe
                  - tel-aviv-yafo
                  - tiberias
                  - tira
                  - tirat-carmel
                  - umm-al-fahm
                  - yavne
                  - yehud-monosson
                  - yokneam-illit
        steps:
         - name: Setup deno
           uses: denoland/setup-deno@main
           with:
             deno-version: v1.10.x
         - name: Check out repo
           uses: actions/checkout@v2
         - run: |
              git reset --hard main
              git pull
         - name: Fetch data
           uses: githubocto/flat@v3
           with:
              http_url: 'http://api.weatherapi.com/v1/current.json?key=${{ secrets.API_KEY }}&q=${{ matrix.package }}-israel&aqi=no'
              downloaded_filename: ./data/${{ matrix.package }}.json
              postprocess: postprocess.js
