name: batch collector
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/batch-collector.yml
jobs:
    batch_print:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package: [\"tel aviv\", \"jerusalem\", \"haifa\"]
        steps:
         - run: |
              echo "${{ matrix.value }}"
