name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: 'http://api.weatherapi.com/v1/current.json?key=${{ secrets.API_KEY }}&q=Tel aviv&aqi=no'
          downloaded_filename: ./data/tel-aviv.json
          postprocess: postprocess.js
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://api.weatherapi.com/v1/current.json?key=${{ secrets.API_KEY }}&q=london&aqi=no
          downloaded_filename: ./data/london.json
          postprocess: postprocess.js
